// var headerTitle = document.getElementById('header-title');
// var parentElement = headerTitle.parentElement;
// var helloText = document.createTextNode('Hello ');
// parentElement.insertBefore(helloText, headerTitle);
// var itemsList = document.getElementById('items');
// var firstItem = itemsList.firstElementChild;
// var helloText2 = document.createTextNode('Hello ');
// itemsList.insertBefore(helloText2, firstItem);
// var lastElementChild = itemsList.lastElementChild;
// var lastChild = itemsList.lastChild;
// var createChild = document.createElement('li');
// var firstElementChild = itemsList.firstElementChild;
// var firstChild = itemsList.firstChild;
// var nextSibling = firstItem.nextSibling;
// var nextElementSibling = firstItem.nextElementSibling;
// var previousSibling = lastElementChild.previousSibling;
// var previousElementSibling = lastElementChild.previousElementSibling;
// var newElement = document.createElement('li');
// newElement.textContent = 'New Item';
// itemsList.appendChild(newElement);

